### ISSUE TITLE
high cpu usage...

### ISSUE THREAD

**Issue by mikeggh** [samwho/spacer#7]
My usage:
cd /var/log/apache
tail -F error.log|spacer -a 30

It ends up with a core being 99%... an strace only shows a blocking read() on the process..

I figured i'd report.. not sure if for some reason high cpu usage is necessary..

**Comment by samwho** [comment]
High CPU usage is definitely not expected. Could you show me a screenshot of where you're seeing this high CPU use?

**Comment by mikeggh** [comment]
![Uploading shot.png…]()

**Comment by mikeggh** [comment]
It seems to have lowered some, only 10%/5% per core for each.. 
![shot2](https://github.com/samwho/spacer/assets/125227868/f8c87223-8109-4ad7-92ae-ea0f1b5f4919)

**Comment by mikeggh** [comment]
It seems to have lowered to 1.7% and 0.6%, which is personally acceptable.. thank you sir for your work..:>
always nice to find new utilities to help after 20yrs of devops:>

**Comment by samwho** [comment]
There was a bug eating up CPU! I found it and fixed it in https://github.com/samwho/spacer/pull/9. Thanks for reporting! v0.1.8 should include the fix. Please reopen this if it doesn't fix it.
