### ISSUE TITLE
dependancy to glibc

### ISSUE THREAD

**Issue by zarkod** [samwho/spacer#8]
When running binary extracted from https://github.com/samwho/spacer/releases/download/v0.1.6/spacer-x86_64-unknown-linux-gnu.tar.gz on fedora 32 I get :
spacer: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by spacer)
spacer: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by spacer)
spacer: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by spacer)
Would be better if spacer was relying on an older version of glibc to be compatible with old systems or if a statically linked version was provided to avoid this.
Regards,
Manuel

**Comment by samwho** [comment]
This was fixed in https://github.com/samwho/spacer/pull/5 but I haven't done a release yet to include those binaries. Let me do that now.

**Comment by samwho** [comment]
Alrighty, the `musl` binaries should be available to download at https://github.com/samwho/spacer/releases/tag/v0.1.7.

I'm going to close this for now, please reopen it if you find that the musl binaries don't work for you. 🙂
